### ISSUE TITLE
unable to run this project

### ISSUE THREAD

**Issue by vishwasT007** [anandpatel0123/MyMovieApp#1]
please help me when I'm doing lng build and lng serve , I'm getting white screen.

**Comment by anandpatel0123** [comment]
Make sure you run npm install before lng dev

**Comment by vishwasT007** [comment]
I did Anand, but I'm unable to launch the app can you please help.

**Comment by vishwasT007** [comment]
I did npm install then lng build, then lng serve, then lng watch.

**Comment by anandpatel0123** [comment]
Sorry for the issue, i accidently removed one Depedency from package.json.
Please clone the code now and check or else you can replace the package.json file from the below code 
`{
   "homepage":"https//anandpatel0123/MyMovieApp",
  "name": "mymovieapp",
  "description": "MyMovieApp",
  "dependencies": {
   "@lightningjs/sdk": "^4.6.1",
    "@lightningjs/ui": "^1.3.7"
    
  },
  "scripts":{
    "predeploy":"lng build",
    "deploy":"gh-pages -d build",
    "build":"lng build"
  },
  "devDependencies": {
    "gh-pages": "^5.0.0"
  }
}
`

**Comment by vishwasT007** [comment]
Thank You so much Anand, can you ping me on WhatsApp 9921329007  if possible.

**Comment by anandpatel0123** [comment]
Hi, Please do not share your Personal details.
We can connect over [linkedIn ](https://www.linkedin.com/in/anandpatel123/)

**Comment by anandpatel0123** [comment]
Hi, Please do not share your Personal details.
We can connect over [linkedIn ](https://www.linkedin.com/in/anandpatel123/)
